<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Passwords must have at least one non alphanumeric character, one digit (0-9), one uppercase (A-Z), one lowercase (a-z), one special character</name>
   <tag></tag>
   <elementGuidId>c25114f7-9bab-4c4f-8420-e927eb5c1be2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d80f2b2c-baec-4002-8e9e-0b5295ef2e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>990827aa-ab53-4a7a-8da1-cad629b38947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>1aaf0622-6c75-4049-af02-e47a7d29da3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer.</value>
      <webElementGuid>3fa493f4-6a30-4e7a-ae8e-cf35151d18a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>6a1bb7ac-f735-4d3a-b6fa-7d9164e5a6da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name']</value>
      <webElementGuid>566412e0-a99b-45d8-b9f3-c3de3b890092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/p</value>
      <webElementGuid>3212e9e9-7802-4b87-a4e4-dd9d91f641cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>4cd73ce5-bbc6-42a6-aba6-1343a393f81c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name' and (text() = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;) or . = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;))]</value>
      <webElementGuid>2051ea15-6ac8-4402-a288-04f195a42eaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
