<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_id(katalon-rec_elementInfoDiv) (2)</name>
   <tag></tag>
   <elementGuidId>da2ae167-3e71-43f7-a2ce-abc3c0d86bf6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#katalon-rec_elementInfoDiv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>60f32d32-83c3-4a08-a0b7-3ffb63a041de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>katalon-rec_elementInfoDiv</value>
      <webElementGuid>e7807b61-3668-4fed-8a67-b1820fc73430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>21cdae95-4661-4b22-97ad-d39e492210db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon-rec_elementInfoDiv&quot;)</value>
      <webElementGuid>87893853-63c8-49d0-bfc7-05904bb7bd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_DEMOQA/iframe_a-gd16rm31azpu</value>
      <webElementGuid>6c448d63-702a-43ef-8bef-c432b462beb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='katalon-rec_elementInfoDiv']</value>
      <webElementGuid>002eba80-33a0-4644-8ea9-45dd1adb363e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon']/div</value>
      <webElementGuid>6180c6e8-010f-4842-94f6-c158bbb51d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>16bcb450-6878-4cb5-b7ab-66fe938556aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'katalon-rec_elementInfoDiv' and (text() = 'id(&quot;katalon-rec_elementInfoDiv&quot;)' or . = 'id(&quot;katalon-rec_elementInfoDiv&quot;)')]</value>
      <webElementGuid>d444a614-099f-4345-90b2-ee36158f4e22</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
