<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_You are already logged in. View your profile</name>
   <tag></tag>
   <elementGuidId>2f3eb20f-dc88-49a7-ae59-cd44b9d36058</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='loading-label']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loading-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>79532f56-5d81-4568-958a-18dae21ab1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-label</value>
      <webElementGuid>5a14ca49-9b6a-4163-b30b-bde767d03372</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loading-label</value>
      <webElementGuid>8ed05a2a-afe7-42c9-bab8-322dc4e5b04a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You are already logged in. View your profile.</value>
      <webElementGuid>be1cb13e-1241-4341-8b86-0dc3d555928f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loading-label&quot;)</value>
      <webElementGuid>0e3c1e74-73d9-4254-b92b-f26c4b52a8aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='loading-label']</value>
      <webElementGuid>17c4e106-0e66-4d0c-8a72-fdcdaf4f2347</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='loading-wrapper']/div/label)[3]</value>
      <webElementGuid>e08a867b-83a2-4c9b-a803-362fb66b02e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/label</value>
      <webElementGuid>a576ec06-4142-4d40-aa4c-4321b7b272c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'loading-label' and (text() = 'You are already logged in. View your profile.' or . = 'You are already logged in. View your profile.')]</value>
      <webElementGuid>0d100ace-fed0-43d0-95e6-319dcf2f1afa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
