<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Passwords must have at least one non alph_e3847b</name>
   <tag></tag>
   <elementGuidId>edaada0d-8070-45ea-809b-42bdbf6f7ea7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[@id='name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>092b2ebb-7f7e-4430-b7f3-24130aa21d3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>fab852c4-cd71-4704-80b0-680e4a8e4b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-1</value>
      <webElementGuid>ce5e7b39-c69e-402c-a2c3-089b1fbe13d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passwords must have at least one non alphanumeric character, one digit ('0'-'9'), one uppercase ('A'-'Z'), one lowercase ('a'-'z'), one special character and Password must be eight characters or longer.</value>
      <webElementGuid>457a258d-e2d3-4b77-ae14-14bdb26043c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;name&quot;)</value>
      <webElementGuid>5c3d5be0-ec6b-4ef3-b0d3-efee84d813d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//p[@id='name']</value>
      <webElementGuid>955b14fc-87f1-4a44-bd25-571d97a6f862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='output']/div/p</value>
      <webElementGuid>d28233aa-c346-4ee6-8966-2d880ccb6bde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>b1ddca21-08ea-46bd-b377-f56d1b976669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@id = 'name' and (text() = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;) or . = concat(&quot;Passwords must have at least one non alphanumeric character, one digit (&quot; , &quot;'&quot; , &quot;0&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;9&quot; , &quot;'&quot; , &quot;), one uppercase (&quot; , &quot;'&quot; , &quot;A&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;Z&quot; , &quot;'&quot; , &quot;), one lowercase (&quot; , &quot;'&quot; , &quot;a&quot; , &quot;'&quot; , &quot;-&quot; , &quot;'&quot; , &quot;z&quot; , &quot;'&quot; , &quot;), one special character and Password must be eight characters or longer.&quot;))]</value>
      <webElementGuid>54ecbb62-d288-4efa-98b6-98b67dcdf74d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
